name: Update LLAPI Folder

on:
  push:
    branches:
      - develop
  schedule:
  - cron:  "*/20 * * * *"
  workflow_dispatch:

jobs:
  update:
    runs-on: ubuntu-latest

    steps:
    - name: Install apt-get utilities
      run: sudo apt-get install sharutils

    - uses: actions/setup-python@v2
      with:
        python-version: '3.9'
        
    - uses: actions/checkout@v2
      with:
        ref: develop

    - name: Git Config
      run: |
        set -euo pipefail
        git config --global user.email "theypsilon@gmail.com"
        git config --global user.name "The CI/CD Bot"

    - name: Update LLAPI Folder
      run: ./.github/update_distribution.sh .

    - name: Commit LLAPI Folder
      run: |
        git checkout -f develop -b main
        git add .
        git commit -m "-"
        git fetch origin main || true

    - name: Push LLAPI Folder DB
      run: ./.github/calculate_db.py
      env:
        DB_ID: llapi_folder
        DB_URL: https://raw.githubusercontent.com/MiSTer-LLAPI/LLAPI_folder_MiSTer/main/llapidb.json.zip
        BASE_FILES_URL: https://raw.githubusercontent.com/MiSTer-LLAPI/LLAPI_folder_MiSTer/%s/
        LATEST_ZIP_URL: https://github.com/MiSTer-LLAPI/LLAPI_folder_MiSTer/archive/refs/heads/main.zip
